language: python
python:
  - "3.7"
sudo: required
dist: xenial
install:
  - sudo apt-get update
  - pwd
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda update -q conda
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - conda create -q --name dpd python=$TRAVIS_PYTHON_VERSION
  - conda install faiss-cpu=1.4.0 -c pytorch --use-local
  - pip install -r deps/requirements.txt

  # update spacy corpi
  - python -m spacy download en

  # setup NLTK corpi
  - python scripts/setup_nltk.py
  # - source env/bin/activate
script:
  # - python -m unittest discover (no need to run twice)
  - python -m unittest discover
cache: pip
cache:
  directories:
  - $HOME/.m2